import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import CustomCursor from "@/Component/custom_cursor/CustomCursor";
import ReduxProvider from "@/redux/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`text-poppins h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <CustomCursor />
       
         <ReduxProvider> <Navbar />{children}</ReduxProvider>
      </body>
    </html>
  );
}
