import "./globals.css";
import Navbar from "@/Component/Navbar";
import CustomCursor from "@/Component/custom_cursor/CustomCursor";
import ReduxProvider from "@/redux/provider";

export const metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`text-poppins h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <CustomCursor />       
         <ReduxProvider> <Navbar />{children}</ReduxProvider>
      </body>
    </html>
  );
}
